name: Probar MyApp en macOS

on:
  workflow_dispatch:   # permite lanzarlo manualmente desde GitHub Actions

jobs:
  test-macos:
    runs-on: macos-latest   # corre en un Mac virtual gratuito

    steps:
      - name: Descargar repo
        uses: actions/checkout@v3

      - name: Mostrar archivos en el repo
        run: ls -R

      - name: Montar DMG
        run: hdiutil attach MyApp.dmg

      - name: Listar aplicaciones montadas
        run: ls /Volumes || true

      - name: Copiar app a /Applications (si existe .app dentro del DMG)
        run: |
          APP_PATH=$(find /Volumes -name "*.app" | head -n 1 || true)
          if [ -n "$APP_PATH" ]; then
            echo "Encontrada app en: $APP_PATH"
            cp -R "$APP_PATH" /Applications/
          else
            echo "⚠️ No se encontró ninguna .app dentro del DMG"
          fi

      - name: Intentar abrir la aplicación
        run: |
          APP_PATH=$(find /Applications -name "*.app" | head -n 1 || true)
          if [ -n "$APP_PATH" ]; then
            echo "Abriendo $APP_PATH..."
            open "$APP_PATH" || true
          else
            echo "⚠️ No se pudo abrir ninguna app"
          fi
