name: Build macOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Build app con PyInstaller
        run: pyinstaller --onefile app.py

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: myapp-macos
          path: dist/*
